version: '3'

services:
  #chess:
    #image: chess
    #environment:
      #PORT: 3000
      #MYSQL_HOST: localhost
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root_password
      #MYSQL_DB: mydatabase
      #DEBUG: false
      #EMAIL_USER: user@outlook.com
      #EMAIL_PASS: 

  mysql-db:
    image: mysql:latest
    ports:
      - '3001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase




