version: '3'

services:
    chess:
        image: chess
        network_mode: 'host'
        environment:
            PORT: 3306
            MYSQL_HOST: 127.0.0.1
            MYSQL_USER: root
            MYSQL_PASSWORD: root_password
            MYSQL_DB: mydatabase
            DEBUG: false
            EMAIL_USER: user@outlook.com
            EMAIL_PASS: password
